aarch64: # target cpu
  cpu_type: "aarch64"
  tarball_url: "https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--glibc--bleeding-edge-2018.07-1.tar.bz2"
  tool_perfix: "aarch64-linux"
  strip_perfix: "aarch64--glibc--bleeding-edge-2018.07-1"
  buildroot_dir: "aarch64-buildroot-linux-gnu"
  toolchain_id: "bootlin_aarch64_toolchain"
  glibc_version: "glibc_2.27.57"
  gcc_version: "8.1.0"

armv7:
  cpu_type: "armeabi-v7a"
  tarball_url: "https://toolchains.bootlin.com/downloads/releases/toolchains/armv7-eabihf/tarballs/armv7-eabihf--glibc--bleeding-edge-2018.07-1.tar.bz2"
  tool_perfix: "arm-linux"
  strip_perfix: "armv7-eabihf--glibc--bleeding-edge-2018.07-1"
  buildroot_dir: "arm-buildroot-linux-gnueabihf"
  toolchain_id: "bootlin_arm_toolchain"
  glibc_version: "glibc_2.27.57"
  gcc_version: "8.1.0"

x86_64:
  cpu_type: "x86_64"
  tarball_url: "https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64-core-i7/tarballs/x86-64-core-i7--glibc--bleeding-edge-2018.07-1.tar.bz2"
  tool_perfix: "x86_64-linux"
  strip_perfix: "x86-64-core-i7--glibc--bleeding-edge-2018.07-1"
  buildroot_dir: "x86_64-buildroot-linux-gnu"
  toolchain_id: "bootlin_x86_64_toolchain"
  glibc_version: "glibc_2.27.57"
  gcc_version: "8.1.0"

i686:
  cpu_type: "i686"
  tarball_url: "https://toolchains.bootlin.com/downloads/releases/toolchains/x86-i686/tarballs/x86-i686--glibc--bleeding-edge-2018.07-1.tar.bz2"
  tool_perfix: "i686-linux"
  strip_perfix: "x86-i686--glibc--bleeding-edge-2018.07-1"
  buildroot_dir: "i686-buildroot-linux-gnu"
  toolchain_id: "bootlin_i686_toolchain"
  glibc_version: "glibc_2.27.57"
  gcc_version: "8.1.0"